package lc;

/**
 * @author zli
 *
 *         Given two strings s and t which consist of only lowercase letters.
 * 
 *         String t is generated by random shuffling string s and then add one more letter at a
 *         random position.
 * 
 *         Find the letter that was added in t.
 * 
 *         Example:
 * 
 *         Input: s = "abcd" t = "abcde"
 * 
 *         Output: e
 * 
 *         Explanation: 'e' is the letter that was added.
 */
public class P389FindTheDifference {


  public char findTheDifference(String s, String t) {
    int OFFSET = 'a';
    int[] sa = new int[26];
    int[] ta = new int[26];

    for (int i = 0; i < s.length(); i++) {
      sa[s.charAt(i) - OFFSET]++;
    }
    for (int i = 0; i < t.length(); i++) {
      ta[t.charAt(i) - OFFSET]++;
    }
    int result = OFFSET;
    for (int i = 0; i < 26; i++) {
      if (ta[i] > sa[i]) {
        result += i;
        break;
      }
    }
    return (char) result;
  }

  public static void main(String[] args) {
    P389FindTheDifference p = new P389FindTheDifference();
    System.out.println(p.findTheDifference("abcd", "acbdt"));
  }

}
